# Generated by Django 2.1.5 on 2019-02-05 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=100)),
                ('secret', models.CharField(max_length=64)),
                ('oauth_token', models.CharField(max_length=100)),
                ('bot_username', models.CharField(max_length=32)),
                ('server_url', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'integration',
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mr_matcher', models.CharField(blank=True, max_length=150)),
                ('mr_failed_content', models.CharField(blank=True, max_length=150)),
                ('mr_accepted_content', models.CharField(blank=True, max_length=150)),
                ('mr_default_assignee', models.CharField(blank=True, max_length=150)),
                ('integration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Integration')),
            ],
            options={
                'db_table': 'preferences',
            },
        ),
    ]
