# Generated by Django 2.1.7 on 2019-03-21 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190212_1619'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='integration',
            table=None,
        ),
        migrations.AlterModelTable(
            name='settings',
            table=None,
        ),
    ]
