export const GET_INTEGRATIONS = "GET_INTEGRATIONS";
export const DELETE_INTEGRATION = "DELETE_INTEGRATION";
export const ADD_INTEGRATION = "ADD_INTEGRATION";

export const GET_ERRORS = "GET_ERRORS";
export const CREATE_MESSAGES = "CREATE_MESSAGES";