export const GET_INTEGRATIONS = "GET_INTEGRATIONS";
export const DELETE_INTEGRATION = "DELETE_INTEGRATION";
export const ADD_INTEGRATION = "ADD_INTEGRATION";

export const GET_ERRORS = "GET_ERRORS";
export const CREATE_MESSAGES = "CREATE_MESSAGES";

export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";